name: Compile and test

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
      with:
        submodules: 'true'
    
    - name: Emscripten setup
      uses: mymindstorm/setup-emsdk@6ab9eb1bda2574c4ddb79809fc9247783eaf9021
      with:
        version: 4.0.18
    
    - name: Compile
      run: ./build.sh
    
    - name: Test
      run: |
        cd sevenzip-wasm
        npm ci
        npm test
