name: Compile and test

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    
    - name: Emscripten setup
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: 4.0.1
    
    - name: Compile
      run: ./build.sh
    
    - name: Test
      run: |
        cd sevenzip-wasm
        npm ci
        npm test
